### ISSUE TITLE
Some UX suggestions

### ISSUE THREAD

**Issue by notNSANE** [fgsfds/Steam-Superheater#10]
* The Main tab is currently empty for me and gives zero information on what to do, I click on "Update List" button and nothing happens either. Should provide help or guidance, or errors if they do happen, in readable text form. Personally I would like to see the entire list of supported games, even if I can't do anything about them, just grey them up until they're installed and actionable?
* In the About, clicking on "check for updates" only shows a brief loading bar and nothing else happens. Should show a confirmation or error in text form somewhere.
* I unzipped and had to do a lot of scrolling to find the executable. Considering moving all the DLLs to a subfolder. Very minor issue.

Other than this, I installed Fallout 1, updated the list, applied the fixt patch, opened the game and everything worked exactly as it should. Grats!

**Comment by fgsfds** [comment]
Thanks for your suggestions. Glad to hear it working at least. 😀

1. Main tab only shows fixes for installed games. I'll think of a way to add non-installed games there.

2. Noted.

3. I'd love that too but so far I couldn't find an easy way to do that with Net Core. I'll look further.

**Comment by bretthysuik** [comment]
For 3) you could publish as a [single-file executable](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli). Be sure to use `<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>` in the csproj to include the native libs in the exe.

**Comment by fgsfds** [comment]
I actually wanted to avoid making a single file. SH downloads updater app when you check for updates, and this updater requires the same dlls as SH. If I make a single file for SH, I will need to do the same for the updater, and this will expand it from 150Kb to 70Mb.

**Comment by fgsfds** [comment]
1. Done https://github.com/fgsfds/Steam-Superheater/pull/11
2. Done https://github.com/fgsfds/Steam-Superheater/pull/12
3. And done https://github.com/fgsfds/Steam-Superheater/pull/12

@bretthysuik @notNSANE Thanks
