### ISSUE TITLE
DXVK integration

### ISSUE THREAD

**Issue by zarif98** [fgsfds/Steam-Superheater#14]
Tons of games also benefit from running DXVK while also being a more involved installation process. Could this also be implemented in the fixes panel? This will allow for games like GTA 4 and Deus Ex to work a lot smoother in modern hardware.

**Comment by fgsfds** [comment]
Is there any list of games that were actually tested and were confirmed to work and benefit from it?

**Comment by zarif98** [comment]
For some games, PCGamingWiki recommends them as well. Here's GTA IV https://www.pcgamingwiki.com/wiki/Grand_Theft_Auto_IV

**Comment by fgsfds** [comment]
Added it to GTA4. Will be gradually adding it to other games that need it.
