### ISSUE TITLE
[Feature Request] Trigger Steam install of games

### ISSUE THREAD

**Issue by Mellified** [fgsfds/Steam-Superheater#26]
For games which are detected in the user's Steam account but not installed it would be nice to have the option to trigger the install from within Superheater. Playnite does this using just the Steam URLs, then checks to see when the game has finished installing.
https://github.com/JosefNemec/Playnite

**Comment by zarif98** [comment]
Or maybe even detect games that are already installed, and fixes can be provided for them. For games that don't have fixes, maybe they can add some user-submitted fixes.

**Comment by fgsfds** [comment]
@Mellified added launch / install game button. It will be available in the next release.

![image](https://github.com/fgsfds/Steam-Superheater/assets/4870330/9f1b850c-e6e8-40e9-abf4-9b9392faced7)

@zarif98 it's already implemented. Editor detect installed games so you can add fixes for them.
