### ISSUE TITLE
Push this app to the Microsoft Store for auto-updates

### ISSUE THREAD

**Issue by zarif98** [fgsfds/Steam-Superheater#27]
Since the Microsoft Store adds support for not just UWP but all sorts of apps, this will be an easy way to have a storefront for this application. I really like the auto-update functionality of the Microsoft Store instead of having it per app. It's annoying to look up the latest version on GitHub, and an auto-updater would make it feel more modern. Apps like Auto Dark Mode also take advantage of this feature on the Microsoft Store instead of having an extra updater within the application.

**Comment by fgsfds** [comment]
There's already a built-in auto update in the app.

**Comment by fgsfds** [comment]
Apparently, you also have to pay for the dev account, and I have no way of doing that. Sadly, no msstore release in the foreseeable future.
