### ISSUE TITLE
Discord link not working?

### ISSUE THREAD

**Issue by zarif98** [fgsfds/Steam-Superheater#33]
Tried to join the discord server and the link is not working? Would love to speak and contribute to the community!

![image](https://github.com/fgsfds/Steam-Superheater/assets/8284304/6b96e265-a1a6-439c-bf3a-9a8cd616a82e)

**Comment by fgsfds** [comment]
Discord, for some idiotic reason, doesn't allow to create invites that don't expire after 30 days, and I completely forgot to update the link. I really need to add a way to automate that.

For now, you can join using this link: https://discord.gg/8KjDS3EKV
